// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQODvRlsbG8hcxtHAKk3PMeD8hu8dZRXA',
    appId: '1:1018698907487:web:477db1e64ba9036fa780ea',
    messagingSenderId: '1018698907487',
    projectId: 'navigaurd-16516',
    authDomain: 'navigaurd-16516.firebaseapp.com',
    storageBucket: 'navigaurd-16516.firebasestorage.app',
    measurementId: 'G-8HJBVF58SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_lt7HmBuh002O4rL19zQqZcB0MELlW3E',
    appId: '1:1018698907487:android:5245248bee991148a780ea',
    messagingSenderId: '1018698907487',
    projectId: 'navigaurd-16516',
    storageBucket: 'navigaurd-16516.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-GdOdPdgnUgBwAWHKV-LsJDXs8edkARw',
    appId: '1:1018698907487:ios:fd0d67eab5851475a780ea',
    messagingSenderId: '1018698907487',
    projectId: 'navigaurd-16516',
    storageBucket: 'navigaurd-16516.firebasestorage.app',
    iosBundleId: 'com.example.navigaurd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-GdOdPdgnUgBwAWHKV-LsJDXs8edkARw',
    appId: '1:1018698907487:ios:fd0d67eab5851475a780ea',
    messagingSenderId: '1018698907487',
    projectId: 'navigaurd-16516',
    storageBucket: 'navigaurd-16516.firebasestorage.app',
    iosBundleId: 'com.example.navigaurd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQODvRlsbG8hcxtHAKk3PMeD8hu8dZRXA',
    appId: '1:1018698907487:web:4489a1ebba5bf4dea780ea',
    messagingSenderId: '1018698907487',
    projectId: 'navigaurd-16516',
    authDomain: 'navigaurd-16516.firebaseapp.com',
    storageBucket: 'navigaurd-16516.firebasestorage.app',
    measurementId: 'G-6JK9V96D6L',
  );
}
